@startuml
scale max 3000 height
title 初期表示時シーケンス図

actor "ログインユーザ" as User
participant "ユーザ編集画面" as UsersEdit
participant "タグ一覧取得API" as TagAPi
participant "ユーザ詳細取得API" as UsersInfoApi
participant "AWS RDS" as Rds

User -> UsersEdit: ユーザ編集画面へアクセス。
UsersEdit -> UsersEdit: ブラウザから\nJWTトークンを取得。

alt トークン無し
  UsersEdit --> User: ログイン画面へリダイレクト。
else トークン記載のuser_roleが0(システム管理者)以外の場合
  UsersEdit --> User: 権限エラーを表示。
end

UsersEdit -> TagAPi: タグ一覧取得APIをリクエスト。
note right TagAPi
  Authorization: Bearer {JWT}
end note

ref over TagAPi
  ミドルウェアで権限チェック(許可された権限:[システム管理者])
end ref

alt 権限チェック成功
  TagAPi -> Rds: タグ一覧情報を取得。
  note right Rds
    SELECT id,name FROM mat_tags;
  end note
  alt 取得成功
    Rds --> TagAPi: データを返却。
  else 取得失敗
    Rds --> TagAPi: エラーを返却。
    TagAPi --> UsersEdit: 500 Internal Server Error
    UsersEdit --> User: サーバーエラーを表示。 
  end
else トークン無し
  TagAPi --> UsersEdit: 401: Unauthoraized
  UsersEdit -> UsersEdit: 保存された情報を削除。
  UsersEdit --> User: ログイン画面へリダイレクト。
else 権限チェック失敗
  TagAPi --> UsersEdit: 403: Forbidden
  UsersEdit --> User: 権限エラーを表示。  
else リクエストパラメータ不正
  TagAPi --> UsersEdit: 400: Bad Request
  UsersEdit --> User: パラメータエラーを表示。
end

UsersEdit -> UsersInfoApi: ユーザ詳細取得APIをリクエスト。
  
note right UsersInfoApi
  Authorization: Bearer {JWT}
end note

ref over UsersInfoApi
  ミドルウェアで権限チェック(許可された権限:[システム管理者])
end ref

alt 権限チェック成功
  UsersInfoApi -> Rds: ユーザIDがクエリパラメータのユーザIDと\n一致するユーザ情報を取得。 
  note right Rds
    SELECT 
      mt_users.id,
      mt_users.email,
      mt_users.name,
      mt_users.user_role,
      mt_users.department,
      mt_users.company,
      mt_users.password,
      mt_users.is_deleted,
    FROM mt_users
    WHERE
      id = クエリパラメータのユーザID;
  end note
  UsersInfoApi -> Rds: ユーザタグ関連情報とタグ情報を取得。
  note right Rds
    SELECT
      mat_tags.id,
      mat_tags.name
    FROM mat_tags
    INNER JOIN
      mt_user_tags
    ON mat_tags.id = mt_user_tags.tag_id
    WHERE
      mt_user_tags = リクエストパラメータのユーザID;
  end note
  alt 取得成功 
    Rds --> UsersInfoApi: データを返却。
    alt ユーザ情報が存在する
      UsersInfoApi --> UsersEdit: 200 OK
    else ユーザ情報が存在しない
      UsersInfoApi --> UsersEdit: 404 Not Found
      UsersEdit --> User: Not Foundエラーを表示。
    end
  else 取得失敗
    Rds --> UsersInfoApi: エラーを返却。
    UsersInfoApi --> UsersEdit: 500 Internal Server Error
    UsersEdit --> User: サーバーエラーを表示。
  end
else JWTトークン不正
  UsersInfoApi --> UsersEdit: 401 Unauthoraized
  UsersEdit -> UsersEdit: 保存された情報を削除。
  UsersEdit --> User: ログイン画面へリダイレクト。
else 権限チェックエラー
  UsersInfoApi --> UsersEdit: 403 Forbidden
  UsersEdit --> User: 権限エラーを表示。
else リクエストパラメータ不正
  UsersInfoApi --> UsersEdit: 400 Bad Request
  UsersEdit --> User: パラメータエラーを表示。
end
@enduml
