@startuml
scale max 3000 height
title インポートボタン押下時シーケンス図

actor ログインユーザ as User
participant "テストケース一覧画面" as TestCase
participant "テストインポート実施画面" as TestImportExecute

User -> TestCase: インポートボタン押下
TestCase -> TestImportExecute: 親のテストグループIDと\n選択したTIDをクエリパラメータで保持しながら、\nテストインポート画面へ遷移する。
@enduml
