@startuml
scale max 3000 height
title 編集ボタン押下時シーケンス図

actor ログインユーザ as User
participant "テストケース一覧画面" as TestCase
participant "テストケース編集画面" as TestCaseRegist

User -> TestCase: 編集ボタン押下
TestCase -> TestCaseRegist: 親のテストグループIDと\n選択したTIDクエリパラメータで保持しながら、\nテストケース編集画面へ遷移する。
@enduml
