@startuml
scale max 3000 height
title 削除ボタン押下時シーケンス図

actor ログインユーザ as User
participant "テストケース一覧画面" as TestCase
participant "テストケース削除API" as TestCaseDeleteApi
participant "AWS RDS" as RDS
participant "AWS S3" as S3

User -> TestCase: 削除ボタン押下
TestCase -> TestCase: 以下のメッセージと削除ボタン、閉じるボタンをモーダルで表示。
note right TestCase
「本当にこのテストケースを削除しますか？
 対象テストケース: XXXX」
 ※XXXX:選択したテストケースのTID
end note

alt 削除ボタンを押下した場合
  TestCase -> TestCaseDeleteApi: テストケース削除APIをリクエスト。
  note right TestCase
    Authorization: Bearer{JWT}
  end note
  TestCaseDeleteApi --> TestCaseDeleteApi: JWTトークンを検証。

  ref over TestCaseDeleteApi
    ミドルウェアで権限チェック(許可された権限[システム管理者、テスト管理者])
  end ref

  alt 権限チェック成功
    TestCaseDeleteApi -> RDS: 削除対象のファイルパスを取得。
    note right RDS
      SELECT
        tcf.file_path
      FROM
        tt_test_case_files tcf
      WHERE
        tcf.tid = リクエストパラメータのTID
      AND NOT EXISTS (
        SELECT
          1
        FROM
          tt_test_case_files other
          WHERE
            other.file_path = tcf.file_path
          AND other.tid != リクエストパラメータのTID
          AND other.is_deleted = false
      );
    end note
    note right RDS
      SELECT
        evidence_path
      FROM
        tt_test_evidences
      WHERE
        test_group_id = リクエストパラメータのTID;
    end note

    alt 取得成功
      RDS --> TestCaseDeleteApi: データを返却。
    else 取得失敗
      RDS --> TestCaseDeleteApi: エラーを返却。
      TestCaseDeleteApi --> TestCase: 500 Internal Sever Error
      TestCase --> User:以下のエラーメッセージをアラートで表示。
      note right User
        「テストケースの削除に失敗しました。再度お試しください。」
      end note
    end
    TestCaseDeleteApi -> RDS: TIDがリクエストパラメータの\nTIDと一致するテストエビデンス情報を削除。
    note right RDS
      DELETE FROM
        tt_test_evidences
      WHERE tid = リクエストパラメータのTID;
    end note
    TestCaseDeleteApi -> RDS: TIDがリクエストパラメータの\nITDと一致するテスト結果履歴情報を削除。
    note right RDS
      DELETE FROM
        tt_test_results_history
      WHERE tid = リクエストパラメータのTID;
    end note
    TestCaseDeleteApi -> RDS: TIDがリクエストパラメータの\nITDと一致するテスト内容情報を削除。
    note right RDS
      DELETE FROM
        tt_contents
      WHERE tid = リクエストパラメータのTID;
    end note
    TestCaseDeleteApi -> RDS: TIDがリクエストパラメータの\nITDと一致するテスト情報ファイル情報を削除。
    note right RDS
      DELETE FROM
        tt_test_case_files
      WHERE tid = リクエストパラメータのTID;
    end note
    TestCaseDeleteApi -> RDS: TIDがリクエストパラメータの\nITDと一致するテストケース情報を削除。
    note right RDS
      DELETE FROM
        tt_test_cases
      WHERE tid = リクエストパラメータのTID;
    end note

    alt 削除が成功
      RDS --> TestCaseDeleteApi: 削除件数を返却
      TestCaseDeleteApi -> S3: 削除対象のファイルパスが該当するファイルを削除。
      TestCaseDeleteApi --> TestCase: 200 OK
      TestCase --> User: テストケース一覧を表示。
    else 削除が失敗
      RDS --> TestCaseDeleteApi: エラーを返却。
      TestCaseDeleteApi --> TestCase: 500 Internal Sever Error
      TestCase --> User: 以下のエラーメッセージをアラートで表示。
      note right User
        テストケースの削除に失敗しました。再度お試しください。
      end note
    end

  else トークン無し
    TestCaseDeleteApi --> TestCase: 401 Unauthorized
    TestCase -> TestCase: 保存された情報を削除。
    TestCase --> User: ログイン画面へリダイレクト。
  else 権限チェック失敗
    TestCaseDeleteApi --> TestCase: 403 Forbidden
    TestCase --> User: 権限エラーを表示。
  else リクエストパラメータ不正
    TestCaseDeleteApi --> TestCase: 400 Bad Request
    TestCase --> User: パラメータエラーを表示。
  end
else 閉じるボタンを押下した場合
  TestCase-> TestCase: 削除確認モーダルを閉じる。
end
@enduml
