@startuml テストケース新規登録_戻るボタン押下時
scale max 3000 height
title 戻るボタン押下時シーケンス図

actor "ログインユーザ" as User
participant "テストケース新規登録画面" as TestCaseRegist
participant "テストケース一覧画面" as TestCase

User -> TestCaseRegist: 戻るボタン押下時
TestCaseRegist -> TestCase: テストケース一覧画面へ遷移する。

@enduml
