@startuml テストグループ編集_戻るボタン押下時
scale max 3000 height
title 戻るボタン押下時シーケンス図

actor "ログインユーザ" as User
participant "テストグループ編集画面" as TestGroupEdit
participant "テストグループ一覧画面" as TestGroup

User -> TestGroupEdit: 戻るボタン押下時
TestGroupEdit -> TestGroup: テストグループ一覧画面へ遷移する。
@enduml
