@startuml テストグループ編集_初期表示時
scale max 3000 height
title 初期表示時シーケンス図

actor "ログインユーザ" as User
participant "テストグループ編集画面" as TestGroupEdit
participant "タグ一覧取得API" as TagsAPI
participant "テストグループ詳細取得API" as TestGroupInfoApi
participant "AWS RDS" as Rds

User -> TestGroupEdit: テストグループ編集画面へアクセス。
TestGroupEdit -> TestGroupEdit: ブラウザからJWTトークンを取得。

alt トークン無し
  TestGroupEdit --> User: ログイン画面へリダイレクト。
else トークン記載のuser_roleが0(システム管理者)、1(テスト管理者)以外の場合
  TestGroupEdit --> User: 権限エラーを表示。
end

TestGroupEdit -> TagsAPI: タグ一覧取得APIをリクエスト
note right TagsAPI
  Authorization: Bearer{JWT}
end note

ref over TagsAPI
  ミドルウェアで権限チェック(許可された権限[システム管理者、テスト管理者])
end ref

alt 権限チェック成功
  TagsAPI -> Rds: タグ情報を全件取得。
  note right of Rds
  SELECT id, name FROM mt_tags;
  end note
  
  alt 取得成功
    Rds --> TagsAPI: データを返却
    TagsAPI --> TestGroupEdit: 200 OK
  else 取得失敗
    Rds -->TagsAPI: エラーを返却。
    TagsAPI --> TestGroupEdit: 500 Internal Server Error
    TestGroupEdit --> User: サーバーエラーを表示。
  end
else トークン無し
  TagsAPI --> TestGroupEdit: 401 Unauthorized
  TestGroupEdit -> TestGroupEdit: 保存された情報を削除
  TestGroupEdit --> User: ログイン画面へリダイレクト。
else 権限チェック失敗
  TagsAPI --> TestGroupEdit: 403 Forbidden
  TestGroupEdit --> User: 権限エラーを表示。
else リクエストパラメータ不正
  TagsAPI --> TestGroupEdit: 400 Bad Request
  TestGroupEdit --> User: パラメータエラーを表示。
end
TestGroupEdit --> TestGroupInfoApi: テストグループ詳細取得API\nをリクエスト。
note right TestGroupInfoApi
  Authorization: Bearer{JWT}
end note

ref over TestGroupInfoApi
  ミドルウェアで権限チェック(許可された権限[システム管理者、テスト管理者])
end ref

alt 権限チェック成功
  TestGroupInfoApi -> Rds: 該当するテストグループ情報を取得。
  note right Rds
    SELECT
      id,
      oem,
      model,
      event,
      variation,
      destination,
      specs,
      test_startdate,
      test_enddate,
      ng_plan_count,
      created_by,
      updated_by
    WHERE
      id = リクエストパラメータのテストグループID;
  end note
  TestGroupInfoApi --> Rds: テストグループタグ関連情報とタグ情報を取得。
  note right Rds
    SELECT
        mt_tags.id,
        mt_tags.name,
        tt_test_group_tags.test_role
    FROM mt_tags
    INNER JOIN
      tt_test_group_tags
    ON mt_tags.id = tt_test_group_tags.tag_id
    WHERE
      tt_test_group_tags.test_group_id = リクエストパラメータのテストグループID;
  end note

  alt 取得成功
    Rds --> TestGroupInfoApi: データを返却。
    TestGroupInfoApi --> TestGroupEdit: 200 OK
    TestGroupEdit --> User: テストケース編集画面を表示。
  else 取得失敗
    Rds --> TestGroupInfoApi: エラーを返却。
    TestGroupInfoApi --> TestGroupEdit: 500 Internal Server Error
    TestGroupEdit --> User: サーバーエラーを返却。
  end
else トークン無し
  TestGroupInfoApi --> TestGroupEdit: 401 Unauthorized
  TestGroupEdit -> TestGroupEdit: 保存された情報を削除
  TestGroupEdit --> User: ログイン画面へリダイレクト。
else 権限チェック失敗
  TestGroupInfoApi --> TestGroupEdit: 403 Forbidden
  TestGroupEdit --> User: 権限エラーを表示。
else リクエストパラメータ不正
  TestGroupInfoApi --> TestGroupEdit: 400 Bad Request
  TestGroupEdit --> User: パラメータエラーを表示。
end
TestGroupEdit --> User :テストグループ編集画面を表示する。
@enduml
