@startuml
scale max 3000 height
title 更新ボタン押下時シーケンス図

actor "ログインユーザ" as User
participant "テストグループ編集画面" as TestGroupEdit
participant "テストグループ編集API" as TestGroupEditApi
participant "AWS RDS" as RDS

User -> TestGroupEdit: 更新ボタン押下。
TestGroupEdit -> TestGroupEdit: バリデーションチェック。
TestGroupEdit -> TestGroupEditApi: テストグループ編集API\nをリクエスト。
note right TestGroupEditApi
  Authorization: Bearer{JWT}
end note

ref over TestGroupEditApi
  ミドルウェアで権限チェック(許可された権限[システム管理者、テスト管理者])
end ref

alt 権限チェック成功
  TestGroupEditApi -> RDS: 入力されたテストグループ情報を更新。
  note right RDS
    UPDATE tt_test_group
    SET
      oem = 入力されたOEM,
      model = 入力された機種,
      event = 入力されたイベント,
      variation = 入力されたバリエーション,
      destination = 入力された仕向,
      specs = 入力された制御仕様名,
      test_startdate = 入力された試験予定期間_開始日,
      test_enddate = 入力された試験予定期間_終了日,
      ng_plan_count = 入力された不具合予定数,
      updated_by = トークンに保存されたユーザID
    WHERE
      id = リクエストパラメータのテストグループID
  end note

  alt 更新成功
    RDS --> TestGroupEditApi: 更新件数を返却。
    
  else 更新失敗
  RDS --> TestGroupEditApi: エラーを返却。
  TestGroupEditApi --> TestGroupEdit: 500 Internal Server Error
  TestGroupEdit --> User: 以下のエラーメッセージをアラートで表示。
      note right User
        「テストグループ更新に失敗しました。再度お試しください。」
      end note
  end
  TestGroupEditApi -> RDS: 該当するテストグループタグ関連情報を削除する。
  note right RDS
  end note
  alt 削除成功
    RDS --> TestGroupEditApi: 削除件数を返却。
  else 削除失敗
    RDS --> TestGroupEditApi: エラーを返却。
    TestGroupEditApi --> TestGroupEdit: 500 Internal Server Error
    TestGroupEdit --> User: 以下のエラーメッセージをアラートで表示。
      note right User
        「テストグループ更新に失敗しました。再度お試しください。」
      end note
  end

  loop タグの数繰り返す
    TestGroupEditApi -> RDS: 入力されたタグからタグIDを取得。
    note right RDS
      SELECT 
        id
      FROM mt_tags
      WHERE
        name = 入力されたタグ;
    end note

    alt 取得成功
      RDS --> TestGroupEditApi: タグIDを返却。
    else 取得失敗
      RDS --> TestGroupEditApi: エラーを返却。
      TestGroupEditApi --> TestGroupEdit: 500 Internal  Server Error
      TestGroupEdit --> User: 以下のエラーメッセージをアラートで表示。
      note right User
        「テストグループ更新に失敗しました。再度お試しください。」
      end note
    end
    TestGroupEditApi -> RDS: テストグループタグ関連情報を登録する。
    note right RDS
      INSERT INTO tt_test_group_tags
      (
        test_group_id,
        tag_id,
        test_role
      )
      VALUES
      (
        リクエストパラメータのテストグループID,
        取得したタグID,
        リクエストパラメータのtest_role
      );
    end note
    alt 登録成功
      RDS --> TestGroupEditApi: 登録件数を返却。
      TestGroupEditApi --> TestGroupEdit: 200 OK
      TestGroupEdit --> User: テストグループ一覧画面へ遷移する。
    else 登録失敗
      RDS --> TestGroupEditApi: エラーを返却。
      TestGroupEditApi --> TestGroupEdit: 500 Internal Server Error
      TestGroupEdit --> User: 以下のエラーメッセージをアラートで表示。
      note right User
        「テストグループ更新に失敗しました。再度お試しください。」
      end note
    end
  end
else トークン無し
  TestGroupEditApi --> TestGroupEdit: 401 Unauthorized
  TestGroupEdit -> TestGroupEdit: 保存された情報を削除。
  TestGroupEdit --> User: ログイン画面へリダイレクト。
else 権限チェック失敗
  TestGroupEditApi --> TestGroupEdit: 403 Forbidden
  TestGroupEdit --> User: 権限エラーを表示。
else リクエストパラメータ不正
  TestGroupEditApi --> TestGroupEdit: 400 Bad Request
  TestGroupEdit --> User: パラメータエラーを表示。
end
@enduml
