@startuml
scale max 3000 height
title 登録ボタン押下時シーケンス図

actor "ログインユーザ" as User
participant "テストグループ複製画面" as TestGroupDuplicate
participant "テストグループ複製API" as TestGroupDuplicateApi
participant "AWS RDS" as RDS

User -> TestGroupDuplicate: 複製ボタン押下。
TestGroupDuplicate -> TestGroupDuplicate: バリデーションチェック

TestGroupDuplicate -> TestGroupDuplicateApi: テストグループ複製API\nをリクエスト。
note right TestGroupDuplicateApi
  Authorization: Bearer{JWT}
end note

ref over TestGroupDuplicateApi
  ミドルウェアで権限チェック(許可された権限[システム管理者、テスト管理者])
end ref

alt 権限チェック成功
  TestGroupDuplicateApi -> TestGroupDuplicateApi: バリデーションチェック
  TestGroupDuplicateApi -> RDS: 該当するテストグループを取得。
  note right RDS
    SELECT 
      id,
      oem,
      model,
      event,
      variation,
      destination,
      specs,
      test_startdate,
      ng_plan_count
    FROM tt_test_groups
    WHERE id = リクエストパラメータのテストグループID
      AND is_deleted = false;
  end note
  RDS --> TestGroupDuplicateApi: 該当するテストグループデータ。

  TestGroupDuplicateApi -> RDS: 新しいテストグループを作成。
  note right RDS
    INSERT INTO tt_test_groups (
        oem,
        model,
        event,
        variation,
        destination,
        specs,
        test_startdate,
        ng_plan_count
    )
    VALUES (
        取得したOEM,
        取得した機種',
        取得したイベント',
        取得したバリエーション',
        取得した仕向,
        取得した制御仕様名,
        取得した試験予定期間_開始日,
        取得した試験予定期間_終了日,
        取得した不具合摘出数予定数
    );
    RETURNING id;
  end note
  RDS --> TestGroupDuplicateApi: テストグループIDを返却

    TestGroupDuplicateApi -> RDS: テストタグ関連を複製。
    note right RDS
      INSERT INTO tt_test_group_tags (
        test_group_id,
        tag_id,
        test_role
      )
      SELECT 
        作成したテストグループID,
        tag_id,
        test_role
      FROM tt_test_group_tags
      WHERE test_group_id = リクエストパラメータのテストグループID
        AND is_deleted = false;
    end note
    RDS --> TestGroupDuplicateApi: 複製完了。



    TestGroupDuplicateApi -> RDS: テストケースを複製。
    note right RDS
      INSERT INTO tt_test_cases (
        test_group_id,
        tid,
        first_layer,
        second_layer,
        third_layer,
        fourth_layer,
        purpose,
        test_procedure
      )
      SELECT 
        作成したテストグループID,
        tid,
        first_layer,
        second_layer,
        third_layer,
        fourth_layer,
        purpose,
        test_procedure
      FROM tt_test_cases
      WHERE test_group_id = リクエストパラメータのテストグループID
        AND is_deleted = false;
    end note
    RDS --> TestGroupDuplicateApi: 複製完了。



    TestGroupDuplicateApi -> RDS: テストケースファイルを複製。
    note right RDS
      INSERT INTO tt_test_case_files (
        test_group_id,
        tid,
        file_type,
        file_no,
        file_name,
        file_path
      )
      SELECT 
        作成したテストグループID,
        tid,
        file_type,
        file_no,
        file_name,
        file_path
      FROM tt_test_case_files
      WHERE test_group_id = リクエストパラメータのテストグループID
        AND is_deleted = false;
    end note
    RDS --> TestGroupDuplicateApi: 複製完了。



    TestGroupDuplicateApi -> RDS: テスト内容を複製。
    note right RDS
      INSERT INTO tt_test_contents (
        test_group_id,
        tid,
        test_case_no,
        test_case,
        expected_value,
        is_target
      )
      SELECT 
        作成したテストグループID,
        tid,
        test_case_no,
        test_case,
        expected_value,
        is_target
      FROM tt_test_contents
      WHERE test_group_id = リクエストパラメータのテストグループID
        AND is_deleted = false;
    end note
    RDS --> TestGroupDuplicateApi: 複製完了。



    TestGroupDuplicateApi -> RDS: テスト結果を複製。
    note right RDS
      INSERT INTO tt_test_results (
        test_group_id,
        tid,
        test_case_no,
        result,
        judgment,
        software_version,
        execution_date,
        executor,
        note
      )
      SELECT 
        作成したテストグループID,
        tid,
        test_case_no,
        result,
        judgment,
        software_version,
        execution_date,
        executor,
        note
      FROM tt_test_results
      WHERE test_group_id = リクエストパラメータのテストグループID
        AND is_deleted = false;
    end note
    RDS --> TestGroupDuplicateApi: 複製完了。



    TestGroupDuplicateApi -> RDS: テスト結果履歴を複製。
    note right RDS
      INSERT INTO tt_test_results_history (
        test_group_id,
        tid,
        test_case_no,
        history_count,
        result,
        judgment,
        software_version,
        execution_date,
        executor,
        note
      )
      SELECT 
        作成したテストグループID,
        tid,
        test_case_no,
        history_count,
        result,
        judgment,
        software_version,
        execution_date,
        executor,
        note
      FROM tt_test_results_history
      WHERE test_group_id = リクエストパラメータのテストグループID
        AND is_deleted = false;
    end note
    RDS --> TestGroupDuplicateApi: 複製完了。



    TestGroupDuplicateApi -> RDS: テストエビデンスを複製。
    note right RDS
      INSERT INTO tt_test_evidences (
        test_group_id,
        tid,
        test_case_no,
        history_count,
        evidence_no,
        evidence_name,
        evidence_path
      )
      SELECT 
        作成したテストグループID,
        tid,
        test_case_no,
        history_count,
        evidence_no,
        evidence_name,
        evidence_path
      FROM tt_test_evidences
      WHERE test_group_id = リクエストパラメータのテストグループID
        AND is_deleted = false;
    end note
    RDS --> TestGroupDuplicateApi: 複製完了。


  RDS --> TestGroupDuplicateApi: 複製成功 (複製したテストグループID)。
  TestGroupDuplicateApi --> TestGroupDuplicate: 201 Created
  TestGroupDuplicate --> User: テストグループ一覧へ遷移する。
else 権限チェック失敗
  TestGroupDuplicateApi --> TestGroupDuplicate: 403 Forbidden
  TestGroupDuplicate --> User: 権限エラーを表示。
else リクエストパラメータ不正
  TestGroupDuplicateApi --> TestGroupDuplicate: 400 Bad Request
  TestGroupDuplicate --> User: パラメータエラーを表示。
end
@enduml