@startuml
scale max 3000 height
title 確認ボタン押下時シーケンス図

actor "ログインユーザ" as User
participant "インポート結果一覧画面" as ImportResult
participant "インポート内容確認" as ImportInfo

User -> ImportResult: 確認ボタンを押下。
ImportResult -> ImportInfo: インポート内容確認画面へ遷移する。
@enduml
