@startuml
scale max 3000 height
title 初期表示時シーケンス図

actor "ログインユーザ" as User
participant "ユーザインポート実施画面" as UserImportExecute

User -> UserImportExecute: ユーザインポート実施画面へアクセス。
UserImportExecute -> UserImportExecute: ブラウザから\nJWTトークンを取得。

alt トークン無し
 UserImportExecute --> User: ログイン画面へリダイレクト。
else トークン記載のuser_roleが0(管理者)以外の場合
 UserImportExecute --> User: 権限エラーを表示。
end
UserImportExecute --> User: ユーザインポート実施画面表示。

@enduml
