@startuml
scale max 3000 height
title 新規登録ボタン押下時シーケンス図

actor "ログインユーザ" as User
participant "テストグループ一覧画面" as TestGroup
participant "テストグループ新規登録画面" as TestGroupRegist

User -> TestGroup: テストグループ新規登録ボタン押下
TestGroup -> TestGroupRegist: テストグループ新規登録画面へ遷移する。
@enduml
