@startuml
scale max 3000 height
title ログアウトボタン押下時シーケンス図

actor "ログインユーザ" as User
participant "Webアプリ画面" as WebApp

User -> WebApp: ログアウトボタンを押下。
WebApp -> WebApp: 保存された情報を削除。
WebApp --> User: ログイン画面へ遷移する。
@enduml
