@startuml
scale max 3000 height
title ユーザ一覧リンクテキスト押下時シーケンス図

actor "ログインユーザ" as User
participant "Webアプリ画面" as WebApp

User -> WebApp: ユーザ一覧リンクテキストを押下。
WebApp --> User: ユーザ一覧画面へ遷移する。
@enduml
