@startuml
scale max 3000 height
title テストグループ情報モーダル_情報取得シーケンス図

actor "ログインユーザ" as User
participant "Webアプリ画面" as WebApp
participant "テストグループ詳細取得API" as TestGroupInfoApi
participant "AWS RDS" as Rds

User -> WebApp: テストグループ情報ボタンを\n表示している画面へアクセス。\n(例：テストケース一覧画面)

WebApp --> TestGroupInfoApi: テストグループ詳細取得API\nをリクエスト。
note right TestGroupInfoApi
  Authorization: Bearer{JWT}
end note

ref over TestGroupInfoApi
  ミドルウェアで権限チェック(許可された権限[システム管理者、テスト管理者、一般])
end ref

alt 権限チェック成功
  TestGroupInfoApi -> Rds: 該当するテストグループ情報を取得。
  note right Rds
    SELECT
      id,
      oem,
      model,
      event,
      variation,
      destination,
      specs,
      test_startdate,
      test_enddate,
      ng_plan_count,
      created_by,
      updated_by
    WHERE
      id = リクエストパラメータのテストグループID;
  end note

  alt 取得成功
    Rds --> TestGroupInfoApi: データを返却。
    TestGroupInfoApi -->  WebApp: 200 OK
  else 取得失敗
    Rds --> TestGroupInfoApi: エラーを返却。
    TestGroupInfoApi -->  WebApp: 500 Internal Server Error
     WebApp --> User: サーバーエラーを表示。
  end
  
else トークン無し
  TestGroupInfoApi -->  WebApp: 401 Unauthorized
   WebApp ->  WebApp: 保存された情報を削除
   WebApp --> User: ログイン画面へリダイレクト。
else 権限チェック失敗
  TestGroupInfoApi -->  WebApp: 403 Forbidden
   WebApp --> User: 権限エラーを表示。
else リクエストパラメータ不正
  TestGroupInfoApi -->  WebApp: 400 Bad Request
   WebApp --> User: パラメータエラーを表示。
end
@enduml
