@startuml
scale max 3000 height
title 戻るボタン押下時シーケンス図

actor "ログインユーザ" as User
participant "ユーザ新規登録画面" as UsersRegist
participant "ユーザ一覧画面" as Users

User -> UsersRegist: 戻るボタン押下時
UsersRegist -> Users: ユーザ一覧画面へ遷移する。
@enduml
