@startuml
scale max 3000 height
title 登録ボタン押下時シーケンス図

actor "ログインユーザ" as User
participant "ユーザ新規登録画面" as UsersRegist
participant "ユーザ新規登録API" as UsersRegistApi
participant "AWS RDS" as Rds

User -> UsersRegist: 登録ボタン押下。
UsersRegist -> UsersRegist: ブラウザから\nJWTトークンを取得。

alt トークン無し
  UsersRegist --> User: ログイン画面へリダイレクト。
else トークン記載のuser_roleが0(システム管理者)以外の場合
  UsersRegist --> User: 権限エラーを表示。
end

UsersRegist -> UsersRegist: バリデーションチェック。
UsersRegist -> UsersRegistApi: ユーザ新規登録APIをリクエスト。
  
note right UsersRegistApi
  Authorization: Bearer {JWT}
end note

ref over UsersRegistApi
  ミドルウェアで権限チェック(許可された権限:[システム管理者])
end ref

alt 権限チェック成功
  UsersRegistApi -> UsersRegistApi: 入力されたパスワードを暗号化。
  UsersRegistApi -> Rds: 入力されたユーザ情報を登録。
  note right Rds
    INSERT INTO mt_users
    (
      email,
      name,
      user_role,
      department,
      company,
      password,
      is_deleted
    )
    VALUES
    (
      入力されたID(メールアドレス),
      入力された氏名,
      入力された部署,
      入力された会社名,
      暗号化されたパスワード,
      false
    )
    RETURNIGN id;
  end note

  alt 登録成功
    Rds -> UsersRegistApi:ユーザIDを返却。

    loop タグの数繰り返す。
      UsersRegistApi -> Rds: 入力したタグ名を条件にタグIDを取得する。
      note right Rds
        SELECT
          id 
        FROM
           mt_tags
        WHERE
          name = 入力したタグ名;
      end note

      alt 取得成功
        Rds --> UsersRegistApi: タグIDを返却。
      else 該当するデータが存在しない
        UsersRegistApi -> Rds: タグ情報を登録。
        note right Rds
          INSERT INTO met_tags(name)
          VALUES
          (入力されたタグ)
          RETURNING id;
        end note
        Rds --> UsersRegistApi: タグIDを返却。
      else 取得失敗
        Rds --> UsersRegistApi: エラーを返却。
        UsersRegistApi --> UsersRegist: 500 Internal Server Error
        UsersRegist --> User: 以下のエラーメッセージを\nアラートで表示する。
        note right User
          「ユーザ登録に失敗しました。再度お試しください。」
        end note 
      end
      UsersRegistApi -> Rds: タグ関連情報を登録。
      note right Rds
        INSERT INTO mt_user_tags
        (
          user_id,
          tag_id
        )
        VALUES
        (
          取得したユーザID
          取得したタグID
        );
      end note
      Rds --> UsersRegistApi: 登録件数を返却
    end 
    UsersRegistApi --> UsersRegist: 201 Created
    UsersRegist --> User: ユーザ一覧画面へ遷移する。
  else 登録失敗
    Rds --> UsersRegistApi: エラーを返却。
    UsersRegistApi --> UsersRegist: 500 Internal Server Error
    UsersRegist --> User: 以下のエラーメッセージを\nアラートで表示する。
    note right User
      「ユーザ登録に失敗しました。再度お試しください。」
    end note 
  end
else JWTトークン不正
  UsersRegistApi --> UsersRegist: 401 Unauthoraized
  UsersRegist -> UsersRegist: 保存された情報を削除。
  UsersRegist --> User: ログイン画面へリダイレクト。
else 権限チェックエラー
  UsersRegistApi --> UsersRegist: 403 Forbidden
  UsersRegist --> User: 権限エラーを表示。
else リクエストパラメータ不正
  UsersRegistApi --> UsersRegist: 400 Bad Request
  UsersRegist --> User: パラメータエラーを表示。
end
@enduml
