@startuml
scale max 3000 height
title インポートボタン押下時シーケンス図

actor "ログインユーザ" as User
participant "ユーザ一覧画面" as Users
participant "ユーザインポート実施画面" as UsersImport

User -> Users: インポートボタン押下
Users -> UsersImport: ユーザインポート画面へ遷移する。
@enduml
