@startuml
scale max 3000 height
title 初期表示時シーケンス図

actor "ログインユーザ" as User
participant "テストグループ新規登録画面" as TestGroupRegist
participant "タグ一覧取得API" as TagsAPI
participant "AWS RDS" as DB

User -> TestGroupRegist: テストグループ新規登録画面へアクセス。
TestGroupRegist -> TestGroupRegist: ブラウザからJWTトークンを取得。

alt トークン無し
  TestGroupRegist --> User: ログイン画面へリダイレクト。
else トークン記載のuser_roleが0(システム管理者)、1(テスト管理者)以外の場合
  TestGroupRegist --> User: 権限エラーを表示。
end

TestGroupRegist -> TagsAPI: タグ一覧取得APIをリクエスト
note right TagsAPI
  Authorization: Bearer{JWT}
end note

ref over TagsAPI
  ミドルウェアで権限チェック(許可された権限[システム管理者、テスト管理者])
end ref

alt 権限チェック成功
  TagsAPI -> DB: タグ情報を全件取得。
  note right of DB
  SELECT id, name FROM mt_tags;
  end note

  alt 取得成功
    DB --> TagsAPI: データを返却。
    TagsAPI --> TestGroupRegist: 200 OK
    TestGroupRegist --> User: テストグループ新規登録画面を表示。
  else 取得失敗
    DB --> TagsAPI: エラーを返却。
    TagsAPI --> TestGroupRegist: 500 Internal Sever Error
    TestGroupRegist --> User: サーバーエラーを表示。
  end
else トークン無し
  TagsAPI --> TestGroupRegist: 401 Unauthorized
  TestGroupRegist -> TestGroupRegist: 保存された情報を削除
  TestGroupRegist --> User: ログイン画面へリダイレクト。
else 権限チェック失敗
  TagsAPI --> TestGroupRegist: 403 Forbidden
  TestGroupRegist --> User: 権限エラーを表示。
else リクエストパラメータ不正
  TagsAPI --> TestGroupRegist: 400 Bad Request
  TestGroupRegist --> User: パラメータエラーを表示。
end
@enduml