@startuml
scale max 3000 height
title 戻るボタン押下時シーケンス図

actor "ログインユーザ" as User
participant "テストグループ新規登録画面" as TestGroupRegist
participant "テストグループ一覧画面" as TestGroup

User -> TestGroupRegist: 戻るボタン押下時
TestGroupRegist -> TestGroup: テストグループ一覧画面へ遷移する。
@enduml
