@startuml
scale max 3000 height
title 戻るボタン押下時シーケンス図

actor "ログインユーザ" as User
participant "ユーザインポート実施画面" as UserImportExecute
participant "ユーザ一覧画面" as Uses

User -> UserImportExecute: 戻るボタン押下
UserImportExecute -> Uses: ユーザ一覧画面へ遷移する。
@enduml
