@startuml
scale max 3000 height
title 初期表示時シーケンス図

actor "ログインユーザ" as User
participant "テストインポート実施画面" as TestImportExecute

User -> TestImportExecute: テストインポート実施画面へアクセス。
TestImportExecute -> TestImportExecute: ブラウザからJWTトークンを取得。

alt トークン無し
  TestImportExecute --> User: ログイン画面へリダイレクト。
else トークン記載のuser_roleが0(システム管理者)、1(テスト管理者)、2(一般)以外の場合
  TestImportExecute --> User: 権限エラーを表示。
end

ref over TestImportExecute
  テストグループ詳細情報を取得。
  ※共通表示部_テストグループ情報モーダル_情報取得処理詳細を参照。
end ref
TestImportExecute --> User: テストインポート実施画面を表示。
@enduml
