@startuml
scale max 3000 height
title インポートボタン押下時シーケンス図

actor "ログインユーザ" as User
participant "テストインポート実施画面" as TestCaseImportExecute
participant "テストケースインポートAPI" as TestCaseImportExecuteApi
participant "AWS Batch" as Batch
participant "AWS RDS" as Rds

User -> TestCaseImportExecute: インポートボタン押下

TestCaseImportExecute -> TestCaseImportExecuteApi: テストケースインポートAPIをリクエスト。
note right TestCaseImportExecuteApi
 Authorization: Bearer{JWT}
end note

ref over TestCaseImportExecuteApi
ミドルウェアで権限チェック(許可された権限:システム管理者)
end ref

alt 権限チェック成功
TestCaseImportExecuteApi -> Batch: テストインポートバッチを実行。\n※バッチ仕様は別紙バッチ設計書を参照。
TestCaseImportExecuteApi -> Rds: インポート結果情報を登録。
note right Rds
 INSERT INTO tt_import_result
 (
  file_name,
  import_date
  import_status,
  executor_name,
  import_type,
  count
 )
 VALUES
 (
  入力したファイル名,
  インポートした日付け,
  0(0:実施中、1:完了、2:エラー),
  ログインユーザ,
  1(0:ユーザ、1:テストケース),
  インポートファイルに記載されているユーザ情報の件数
 )
end note

alt 登録成功
 Rds --> TestCaseImportExecuteApi: 登録件数を返却。
 TestCaseImportExecuteApi -> TestCaseImportExecute: 201 Created 
 TestCaseImportExecute --> User: インポート結果一覧画面へ遷移する。
else 登録失敗
 Rds --> TestCaseImportExecuteApi: エラーを返却。
 TestCaseImportExecuteApi --> TestCaseImportExecute: 500 Internal Server Error
 TestCaseImportExecute -> TestCaseImportExecute: 以下のエラーメッセージをアラートで表示する。
 note right TestCaseImportExecute
  テストインポートに失敗しました。再度お試しください。
 end note
end

else トークン無し
TestCaseImportExecuteApi --> TestCaseImportExecute: 401 Unauthorized
TestCaseImportExecute -> TestCaseImportExecute: 保存されたトークンを削除。
TestCaseImportExecute --> User: ログイン画面へリダイレクト。
else 権限チェック失敗
TestCaseImportExecuteApi --> TestCaseImportExecute: 403 Forbidden
TestCaseImportExecute --> User: 権限エラーを表示。
else リクエストパラメータ不正
TestCaseImportExecuteApi --> TestCaseImportExecute: 400 Bad Request
TestCaseImportExecute --> User: パラメータエラーを表示。
end

@enduml

