@startuml
title 初期表示時シーケンス図
actor "ログインユーザー" as User
participant "テストケース結果登録画面" as Screen
participant "テストケース詳細取得API" as CaseAPI
participant "テスト結果取得API" as ResultAPI
participant "AWS RDS" as DB
participant "S3ファイルダウンロードAPI" as S3API
participant "AWS S3" as S3

User -> Screen: テストケース結果登録画面へアクセス
Screen -> Screen: ブラウザからJWTトークンを取得。

opt トークン無し
  Screen --> User: ログイン画面へリダイレクト。
else トークン記載のuser_roleが0(システム管理者)、1(テスト管理者)、2(一般)以外の場合
  Screen --> User: 権限エラーを表示。
end

ref over Screen
  テストグループ詳細情報を取得。
  ※共通表示部_テストグループ情報モーダル_情報取得処理詳細を参照。
end ref

Screen -> CaseAPI: テストケース詳細取得APIをリクエスト。
note right CaseAPI
  Authorization: Bearer{JWT}
end note

ref over CaseAPI
  ミドルウェアで権限チェック(許可された権限[システム管理者、テスト管理者、一般])
end ref
alt 権限あり
  CaseAPI -> DB: テストケース情報を取得。
  note right of DB
  SELECT 
      tc.test_group_id,
      tc.tid,
      tc.first_layer,
      tc.second_layer,
      tc.third_layer,
      tc.fourth_layer,
      tc.purpose,
      tc.request_id,
      tc.test_procedure,
      tc.created_at,
      tc.updated_at,
      tcf.file_name,
      tcf.file_path,
      tcf.file_type
  FROM 
      tt_test_cases tc
  LEFT JOIN 
      tt_test_case_files tcf
  ON 
      tc.test_group_id = tcf.test_group_id AND tc.tid = tcf.tid
  WHERE 
      tc.test_group_id = リクエストパラメータのtest_group_id 
      AND tc.tid = リクエストパラメータのTID;
  end note
  alt 取得成功
    DB --> CaseAPI: データを返却。
    CaseAPI --> Screen: 200 OK
  else 取得失敗
    DB --> CaseAPI: エラーを返却
    CaseAPI --> Screen: 500 Internal Server Error
    Screen --> User: サーバーエラーを表示。
  end
else トークン無し
  CaseAPI --> Screen: 401 Unauthorized
  Screen -> Screen: 保存された情報を削除
  Screen --> User: ログイン画面へリダイレクト。
else 権限チェック失敗
  CaseAPI --> Screen: 403 Forbidden
  Screen --> User: 権限エラーを表示。
else リクエストパラメータ不正
  CaseAPI --> Screen: 400 Bad Request
  Screen --> User: パラメータエラーを表示。
end
Screen -> ResultAPI: テスト結果取得APIをリクエスト。
note right ResultAPI
  Authorization: Bearer{JWT}
end note

ref over ResultAPI
  ミドルウェアで権限チェック(許可された権限[システム管理者、テスト管理者、一般])
end ref

alt 権限チェック成功
  ResultAPI -> DB: テストケース結果情報を取得。
  note right of DB
    SELECT tc.*, tr.judgment, tr.execution_date
    FROM tt_test_contents tc
    LEFT JOIN tt_test_results tr
    ON tc.test_content_id = tr.test_content_id
    WHERE tc.tid = リクエストパラメータのTID
  end note
  
  alt 取得成功
    DB --> ResultAPI: データを返却
    ResultAPI -> Screen: 200 OK
  else 取得失敗
    DB --> ResultAPI: エラーを返却
    ResultAPI --> Screen: 500 Internal Server Error
    Screen --> User: サーバーエラーを表示。
  end
else トークン無し
  CaseAPI --> Screen: 401 Unauthorized
  Screen -> Screen: 保存された情報を削除
  Screen --> User: ログイン画面へリダイレクト。
else 権限チェック失敗
  CaseAPI --> Screen: 403 Forbidden
  Screen --> User: 権限エラーを表示。
else リクエストパラメータ不正
  CaseAPI --> Screen: 400 Bad Request
  Screen --> User: パラメータエラーを表示。
end
Screen -> S3API: S3ファイルダウンロードAPIをリクエスト。
note right S3API
  Authorization: Bearer{JWT}
end note

ref over S3API
  ミドルウェアで権限チェック(許可された権限[システム管理者、テスト管理者、一般])
end ref

alt 権限チェック成功
  S3API -> S3: S3オブジェクトの署名付きURLを生成。

  alt 生成成功
    S3 --> S3API: 署名付きURLを返却。
    S3API -> Screen: 200 OK
    Screen -> User: テストケース結果登録画面表示
  else 生成失敗
    S3 --> S3API: エラーを返却。
    S3API -> Screen: 500 Internal Server Error
    Screen --> User: サーバーエラーを表示。
  end
else トークン無し
  S3API --> Screen: 401 Unauthorized
  Screen -> Screen: 保存された情報を削除
  Screen --> User: ログイン画面へリダイレクト。
else 権限チェック失敗
  S3API --> Screen: 403 Forbidden
  Screen --> User: 権限エラーを表示。
else リクエストパラメータ不正
  S3API --> Screen: 400 Bad Request
  Screen --> User: パラメータエラーを表示。
end
@enduml